---
spring:
    config:
        activate:
            on-profile: local
application:
  name: wmf
server:
  port: 8080

management:
  security:
    enabled: false

---
spring:
    config:
        activate:
            on-profile: DEV
application:
  name: wmf
server:
  address: insertDEVHostNameHere
  port: 443   

management:
  security:
    enabled: false

---
spring:
    config:
        activate:
            on-profile: UAT
application:
  name: wmf
server:
  address: insertUATHostNameHere
  port: 443   

management:
  security:
    enabled: false 

---
spring:
    config:
        activate:
            on-profile: INT
application:
  name: wmf
server:
  address: insertINTHostNameHere
  port: 443   

management:
  security:
    enabled: false 

---
spring:
    config:
        activate:
            on-profile: STAGING
application:
  name: wmf
server:
  address: insertStagingHostNameHere
  port: 443   

management:
  security:
    enabled: false 

---
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([trace=%X{X-Trace-Id:-},span=%X{X-Span-Id:-}]){yellow} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%replace(%xException){'\n','\u2028'}%nopex%n"
  level:
     io:
        pivotal: DEBUG
     com:
        netflix: FATAL
     org:
        springframework:
           web: WARN
           cloud: WARN 
